[book]
authors = ["jzyong"]
language = "cn"
multilingual = false
src = ""
description = "快节奏多人联网游戏Demo，UGK-Server：unity、go、kcp server " # A description for the book, which is added as meta information in the html <head> of each page
title = "\"ugk-server doc\""

[build]
build-dir = "../../docs"          # the directory where the output is placed
create-missing = true             # whether or not to create missing pages
use-default-preprocessors = true  # use the default preprocessors

[output.html]
git-repository-url = "https://github.com/jzyong/ugk-server"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
