// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: game_galactic_kittens.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GalacticKittensMatchServiceClient is the client API for GalacticKittensMatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GalacticKittensMatchServiceClient interface {
	// 玩家服务器列表
	PlayerServerList(ctx context.Context, in *GalacticKittensPlayerServerListRequest, opts ...grpc.CallOption) (*GalacticKittensPlayerServerListResponse, error)
	// 游戏完成
	GameFinish(ctx context.Context, in *GalacticKittensGameFinishRequest, opts ...grpc.CallOption) (*GalacticKittensGameFinishResponse, error)
}

type galacticKittensMatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGalacticKittensMatchServiceClient(cc grpc.ClientConnInterface) GalacticKittensMatchServiceClient {
	return &galacticKittensMatchServiceClient{cc}
}

func (c *galacticKittensMatchServiceClient) PlayerServerList(ctx context.Context, in *GalacticKittensPlayerServerListRequest, opts ...grpc.CallOption) (*GalacticKittensPlayerServerListResponse, error) {
	out := new(GalacticKittensPlayerServerListResponse)
	err := c.cc.Invoke(ctx, "/GalacticKittensMatchService/playerServerList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galacticKittensMatchServiceClient) GameFinish(ctx context.Context, in *GalacticKittensGameFinishRequest, opts ...grpc.CallOption) (*GalacticKittensGameFinishResponse, error) {
	out := new(GalacticKittensGameFinishResponse)
	err := c.cc.Invoke(ctx, "/GalacticKittensMatchService/gameFinish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GalacticKittensMatchServiceServer is the server API for GalacticKittensMatchService service.
// All implementations must embed UnimplementedGalacticKittensMatchServiceServer
// for forward compatibility
type GalacticKittensMatchServiceServer interface {
	// 玩家服务器列表
	PlayerServerList(context.Context, *GalacticKittensPlayerServerListRequest) (*GalacticKittensPlayerServerListResponse, error)
	// 游戏完成
	GameFinish(context.Context, *GalacticKittensGameFinishRequest) (*GalacticKittensGameFinishResponse, error)
	mustEmbedUnimplementedGalacticKittensMatchServiceServer()
}

// UnimplementedGalacticKittensMatchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGalacticKittensMatchServiceServer struct {
}

func (UnimplementedGalacticKittensMatchServiceServer) PlayerServerList(context.Context, *GalacticKittensPlayerServerListRequest) (*GalacticKittensPlayerServerListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayerServerList not implemented")
}
func (UnimplementedGalacticKittensMatchServiceServer) GameFinish(context.Context, *GalacticKittensGameFinishRequest) (*GalacticKittensGameFinishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameFinish not implemented")
}
func (UnimplementedGalacticKittensMatchServiceServer) mustEmbedUnimplementedGalacticKittensMatchServiceServer() {
}

// UnsafeGalacticKittensMatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GalacticKittensMatchServiceServer will
// result in compilation errors.
type UnsafeGalacticKittensMatchServiceServer interface {
	mustEmbedUnimplementedGalacticKittensMatchServiceServer()
}

func RegisterGalacticKittensMatchServiceServer(s grpc.ServiceRegistrar, srv GalacticKittensMatchServiceServer) {
	s.RegisterService(&GalacticKittensMatchService_ServiceDesc, srv)
}

func _GalacticKittensMatchService_PlayerServerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GalacticKittensPlayerServerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalacticKittensMatchServiceServer).PlayerServerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GalacticKittensMatchService/playerServerList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalacticKittensMatchServiceServer).PlayerServerList(ctx, req.(*GalacticKittensPlayerServerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalacticKittensMatchService_GameFinish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GalacticKittensGameFinishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalacticKittensMatchServiceServer).GameFinish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GalacticKittensMatchService/gameFinish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalacticKittensMatchServiceServer).GameFinish(ctx, req.(*GalacticKittensGameFinishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GalacticKittensMatchService_ServiceDesc is the grpc.ServiceDesc for GalacticKittensMatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GalacticKittensMatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GalacticKittensMatchService",
	HandlerType: (*GalacticKittensMatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "playerServerList",
			Handler:    _GalacticKittensMatchService_PlayerServerList_Handler,
		},
		{
			MethodName: "gameFinish",
			Handler:    _GalacticKittensMatchService_GameFinish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game_galactic_kittens.proto",
}
